### ISSUE TITLE
simanticdb doesn't index .zip files with java library

### ISSUE THREAD

**Issue by irbis** [alexott/cedet#1]
Every time when LALR parses java class there is an error:

Classpath: "... /jmock-cglib-1.0.1.zip" not found

**Comment by alexott** [comment]
can you check this in the devel branch?

**Comment by irbis** [comment]
There is other message:

...WebRoot/WEB-INF/lib/jmock-cglib-1.0.1.zip: No such file or directory

And it doesn't connect with path to the file because previous file 
...WebRoot/WEB-INF/lib/xmlunit-1.0.jar
from the list of files locates successfully.

**Comment by alexott** [comment]
Ok, I will backport it to main branch then - thank you

**Comment by irbis** [comment]
Issue still here. I've updated my previous comment.

**Comment by alexott** [comment]
Hmmm, ok - I'll try to reproduce this on my machine

**Comment by alexott** [comment]
Hi

I've just checked the fix, and it works for me with very simple project where I renamed one of jars into .zip. Can you check your `PATH`, etc. - maybe `javap` or other program isn't found by CEDET? Can you enable 'Debug on errror' and post stacktrace here?

**Comment by irbis** [comment]
It's strange but emacs didn't enter into debug mode with 

(setq debug-on-error 1)

so, I turned on debug-on-message:

(setq debug-on-message "jmock-cglib-1.0.1.zip")

stack trace I got can be found here:
http://yadi.sk/d/dUxmtyBo7jHRt

Hope this will help.
To be sure I tried to open 'jmock-cglib-1.0.1.zip' with jar utility and it works:

$ jar -tf jmock-cglib-1.0.1.zip 
META-INF/
META-INF/MANIFEST.MF
org/
org/jmock/
org/jmock/cglib/
org/jmock/cglib/CGLIBCoreMock.class
org/jmock/cglib/Mock.class
org/jmock/cglib/MockObjectTestCase.class
META-INF/INDEX.LIST

**Comment by irbis** [comment]
Also, jmock-cglib-1.0.1.zip can be found http://yadi.sk/d/6avnuYVn7jI-r

**Comment by alexott** [comment]
CEDET was compiled after update from repo? Emacs was restarted? Basically the change was very simple - it's enough to copy it into db-javap.el, and evaluate buffer with `M-x eval-buffer`

**Comment by irbis** [comment]
It was my mistake. You told about devel branch. I tested master :( (not enought experience to work with git), sorry. It works. Thanks.

**Comment by alexott** [comment]
no problem - I'll merge it into master today, and will commit upstream
