### ISSUE TITLE
CEDET completion improvement

### ISSUE THREAD

**Issue by tuhdo** [alexott/cedet#3]
Hi,

Auto-complete-clang allows querying of multiple C++ overloaded function signatures if there is any. Furthermore, it allows argument insertions, not just simply symbol insertion; we can move forward/backward through function parameters and edit it (similar to yasnippet). It would be nice if CEDET can display multiple interfaces with semantic-ia-show-summary and argument insertion.

![clang](https://raw.github.com/brianjcj/auto-complete-clang/master/screenshot/clang-1.png)

Argument insertion and return type:

![clang_arg_insert](https://f.cloud.github.com/assets/4818719/2347065/b9dfb31c-a548-11e3-9f47-f149e5528ed7.jpg)

I tried to subscribe to cedet-devel but nothing happened, so I write here. Hope it reaches you.

**Comment by tuhdo** [comment]
This package implements what I want: https://github.com/abo-abo/function-args

It should be incorporated into the next version of CEDET.

**Comment by alexott** [comment]
I remember that it was discussed in the mailing list, but I don't know, if author submitted legal papers or not - the CEDET is included into GNU Emacs, so the rights should be assigned to FSF...

I would recommend you to sign to mailing list, and discuss such questions there...

**Comment by tuhdo** [comment]
If that is the case, CEDET team should contact the author. After all, he contributes his package for free, so I don't think he will hesitate to contribute to CEDET, since he is contributing to it indirectly. Though I don't know if the procedure is complicated or not.

Anyway, I subscribed to cedet-devel https://lists.sourceforge.net/lists/listinfo/cedet-devel but got no reply and I could not create anything there.

**Comment by alexott** [comment]
Author of this package already discussed this package in the mailing
list... I don't know about the status of it, and sometimes the procedure
could take relatively long time.

On Friday, March 7, 2014, tuhdo notifications@github.com wrote:

> If that is the case, CEDET team should contact the author. After all, he
> contributes his package for free, so I don't think he will hesitate to
> contribute to CEDET, since he is contributing to it indirectly. Though I
> don't know if the procedure is complicated or not.
> 
> Anyway, I subscribed to cedet-devel
> https://lists.sourceforge.net/lists/listinfo/cedet-devel but got no reply
> and I could not create anything there.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/alexott/cedet/issues/3#issuecomment-37053663
> .

## 

With best wishes,                    Alex Ott
http://alexott.net/
Twitter: alexott_en (English), alexott (Russian)
Skype: alex.ott

**Comment by tuhdo** [comment]
Ah I see. Thanks for the info. In the meantime, I will use it as a separate package then. Would be more convenient if it is built into CEDET.

Btw, CEDET should provide a default configuration, "battery included". I think many people are using your configuration (myself including), so I hope that it will get incorporated into future CEDET as well. It should only take a function to setup, and if they want to further customize (i.e. integration with Ctags, Cscope...) then there should be a short and simple guide for adding relevant features.
